### ISSUE TITLE
Refactor the world class and pull out all the frame bits

### ISSUE THREAD

**Issue by shakedown-street** [shakedown-street/Squire-Framework#2]
Currently the 'world' class just acts as a JComponent, and so theres really no reason to call it 'World'. Also it is responsible for the JFrame being started, which I don't like.

**Comment by A-Sharp-C** [comment]
Currently the 'world' class just acts as a JComponent, and so theres really no reason to call it 'World'.  Also it is responsible for the JFrame being started, which I don't like.
